version: '1'

services:
  api:
    container_name: api
    command: npm run start:prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    # environment:
    #   - DB_HOST=db
    #   - DB_NAME=swapi
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=123321
    build: .
    restart: always
    ports:
      - 3005:3005
    links:
      - db
  db:
    container_name: db 
    image: mysql
    ports: 
      - 3306:3306
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "0.0.0.0", "--silent"]
      interval: 30s
      retries: 20
      start_period: 10s
    environment:
      - MYSQL_ROOT_PASSWORD=123321
      - MYSQL_DATABASE=swapi
      - MYSQL_ROOT_HOST=%
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - internal

networks:
  internal: