version: '2'

services:
  api:
    container_name: api
    command: bash -c "npm run migration:run && npm run seed:up && npm run start:prod"
    depends_on:
      db:
        condition: service_healthy
    build: .
    restart: always
    ports:
      - $API_PORT:$API_PORT
    env_file:
      - .env
  db:
    container_name: db 
    image: mysql
    ports: 
      - $DB_PORT:$DB_PORT
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "0.0.0.0", "--silent"]
      interval: 30s
      retries: 30
      start_period: 10s
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_HOST=%
    env_file:
      - .env
    command: '--default-authentication-plugin=mysql_native_password'